version: "3.8"
services:

  money-counter-frontend:
    hostname: money-counter-frontend
    ports:
      - 3000
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: money-counter-frontend
    networks:
      - default
      - bcp_default

networks:
  default:
    driver: bridge
  bcp_default:
    external: true