version: "3.8"
services:

  money-counter-frontend:
    hostname: money-counter-frontend
    ports:
      - 3000
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: money-counter-frontend
    environment:
      - GOAL=1000
      - BASE=https://moneycounter.stepes.dev
      - STRIPE_SECRET_KEY=sk_test_51OAIdaEe5fhFnrPogFyI38qqBofhu0hh1SpZ1F6pWtBfRy2tLqHdY3KGOlKivmYxIvpT53E2Gns63OHVWkzz56CD007q2Te1I5
      - DATABASE_URL="file:./dev.db"
    networks:
      - default
      - bcp_default

networks:
  default:
    driver: bridge
  bcp_default:
    external: true